"""initial schema

Revision ID: 65fcdab61618
Revises:
Create Date: 2026-08-27 09:16:21.670178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65fcdab61618"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_items",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("stock_tracked", sa.Boolean(), nullable=False),
        sa.Column("stock_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("low_stock_threshold", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("catalog_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_catalog_items_kind"), ["kind"], unique=False)

    op.create_table(
        "employees",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_employees_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_employees_username"), ["username"], unique=True)

    op.create_table(
        "idempotency_records",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=120), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "members",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_phone"), ["phone"], unique=True)

    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_settings_key"), ["key"], unique=True)

    op.create_table(
        "terminals",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("printer_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("terminals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_terminals_code"), ["code"], unique=True)

    op.create_table(
        "wristbands",
        sa.Column("number", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wristbands", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wristbands_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_wristbands_status"), ["status"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chain_index", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=True),
        sa.Column("terminal_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("current_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["terminals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("current_hash"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_chain_index"), ["chain_index"], unique=True)
        batch_op.create_index(batch_op.f("ix_audit_logs_employee_id"), ["employee_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_type"), ["entity_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_request_id"), ["request_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_terminal_id"), ["terminal_id"], unique=False)

    op.create_table(
        "inventory_movements",
        sa.Column("catalog_item_id", sa.String(length=36), nullable=False),
        sa.Column("movement_type", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("reference_type", sa.String(length=40), nullable=True),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("inventory_movements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_movements_catalog_item_id"), ["catalog_item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_movements_movement_type"), ["movement_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_movements_reference_id"), ["reference_id"], unique=False)

    op.create_table(
        "member_passes",
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("remaining_count", sa.Integer(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("member_passes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_member_passes_member_id"), ["member_id"], unique=False)

    op.create_table(
        "shifts",
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("terminal_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("opening_cash", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expected_cash", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("actual_cash", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("difference", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["terminals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shifts_employee_id"), ["employee_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shifts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_shifts_terminal_id"), ["terminal_id"], unique=False)

    op.create_table(
        "visits",
        sa.Column("wristband_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("opened_by_id", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wristband_id"],
            ["wristbands.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_visits_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_visits_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_visits_wristband_id"), ["wristband_id"], unique=False)
        batch_op.create_index(
            "uq_visits_active_wristband",
            ["wristband_id"],
            unique=True,
            postgresql_where=sa.text("status IN ('open', 'settling')"),
            sqlite_where=sa.text("status IN ('open', 'settling')"),
        )

    op.create_table(
        "order_items",
        sa.Column("visit_id", sa.String(length=36), nullable=False),
        sa.Column("catalog_item_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("service_employee_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("voided_by_id", sa.String(length=36), nullable=True),
        sa.Column("void_reason", sa.String(length=255), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_items_catalog_item_id"), ["catalog_item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_items_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_items_visit_id"), ["visit_id"], unique=False)

    op.create_table(
        "settlements",
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("terminal_id", sa.String(length=36), nullable=False),
        sa.Column("shift_id", sa.String(length=36), nullable=True),
        sa.Column("member_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["terminals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("settlements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settlements_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_settlements_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_settlements_shift_id"), ["shift_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_settlements_status"), ["status"], unique=False)

    op.create_table(
        "pass_ledgers",
        sa.Column("member_pass_id", sa.String(length=36), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(length=30), nullable=False),
        sa.Column("settlement_id", sa.String(length=36), nullable=True),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_pass_id"],
            ["member_passes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pass_ledgers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pass_ledgers_member_pass_id"), ["member_pass_id"], unique=False)

    op.create_table(
        "payments",
        sa.Column("settlement_id", sa.String(length=36), nullable=False),
        sa.Column("shift_id", sa.String(length=36), nullable=True),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("original_payment_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payments_method"), ["method"], unique=False)
        batch_op.create_index(batch_op.f("ix_payments_settlement_id"), ["settlement_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payments_shift_id"), ["shift_id"], unique=False)

    op.create_table(
        "print_jobs",
        sa.Column("settlement_id", sa.String(length=36), nullable=False),
        sa.Column("terminal_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("printed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["terminals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("print_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_print_jobs_settlement_id"), ["settlement_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_print_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_print_jobs_terminal_id"), ["terminal_id"], unique=False)

    op.create_table(
        "settlement_visits",
        sa.Column("settlement_id", sa.String(length=36), nullable=False),
        sa.Column("visit_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
        ),
        sa.PrimaryKeyConstraint("settlement_id", "visit_id"),
    )
    op.create_table(
        "stored_value_ledgers",
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("entry_type", sa.String(length=30), nullable=False),
        sa.Column("payment_method", sa.String(length=30), nullable=True),
        sa.Column("shift_id", sa.String(length=36), nullable=True),
        sa.Column("settlement_id", sa.String(length=36), nullable=True),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("stored_value_ledgers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stored_value_ledgers_entry_type"), ["entry_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_stored_value_ledgers_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stored_value_ledgers_shift_id"), ["shift_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_value_ledgers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stored_value_ledgers_shift_id"))
        batch_op.drop_index(batch_op.f("ix_stored_value_ledgers_member_id"))
        batch_op.drop_index(batch_op.f("ix_stored_value_ledgers_entry_type"))

    op.drop_table("stored_value_ledgers")
    op.drop_table("settlement_visits")
    with op.batch_alter_table("print_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_print_jobs_terminal_id"))
        batch_op.drop_index(batch_op.f("ix_print_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_print_jobs_settlement_id"))

    op.drop_table("print_jobs")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_shift_id"))
        batch_op.drop_index(batch_op.f("ix_payments_settlement_id"))
        batch_op.drop_index(batch_op.f("ix_payments_method"))

    op.drop_table("payments")
    with op.batch_alter_table("pass_ledgers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pass_ledgers_member_pass_id"))

    op.drop_table("pass_ledgers")
    with op.batch_alter_table("settlements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settlements_status"))
        batch_op.drop_index(batch_op.f("ix_settlements_shift_id"))
        batch_op.drop_index(batch_op.f("ix_settlements_number"))
        batch_op.drop_index(batch_op.f("ix_settlements_member_id"))

    op.drop_table("settlements")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_visit_id"))
        batch_op.drop_index(batch_op.f("ix_order_items_status"))
        batch_op.drop_index(batch_op.f("ix_order_items_catalog_item_id"))

    op.drop_table("order_items")
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_visits_active_wristband",
            postgresql_where=sa.text("status IN ('open', 'settling')"),
            sqlite_where=sa.text("status IN ('open', 'settling')"),
        )
        batch_op.drop_index(batch_op.f("ix_visits_wristband_id"))
        batch_op.drop_index(batch_op.f("ix_visits_status"))
        batch_op.drop_index(batch_op.f("ix_visits_member_id"))

    op.drop_table("visits")
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shifts_terminal_id"))
        batch_op.drop_index(batch_op.f("ix_shifts_status"))
        batch_op.drop_index(batch_op.f("ix_shifts_employee_id"))

    op.drop_table("shifts")
    with op.batch_alter_table("member_passes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_member_passes_member_id"))

    op.drop_table("member_passes")
    with op.batch_alter_table("inventory_movements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_movements_reference_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_movements_movement_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_movements_catalog_item_id"))

    op.drop_table("inventory_movements")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_terminal_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_request_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_employee_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_chain_index"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("wristbands", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wristbands_status"))
        batch_op.drop_index(batch_op.f("ix_wristbands_number"))

    op.drop_table("wristbands")
    with op.batch_alter_table("terminals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_terminals_code"))

    op.drop_table("terminals")
    with op.batch_alter_table("system_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_settings_key"))

    op.drop_table("system_settings")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_phone"))

    op.drop_table("members")
    op.drop_table("idempotency_records")
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employees_username"))
        batch_op.drop_index(batch_op.f("ix_employees_role"))

    op.drop_table("employees")
    with op.batch_alter_table("catalog_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_items_kind"))

    op.drop_table("catalog_items")
    # ### end Alembic commands ###
